### PR TITLE
Create new A-Z List of Collections page: Desktop #277

### PR DESCRIPTION
**Pull request by snehagunduraoUL**

### CODE REVIEW

**Comment by rschwab** [comment]
This looks ready to merge to me. With this done I think it makes sense to confirm with the team what they want done with the main menu link "Browse Collections". It remains going to the homepage for now, but maybe they want that changed.

**Comment by snehagunduraoUL** [comment]
Thanks for the review Ryan! will confirm with Rachel on that.

**Comment by rmjaffe** [comment]
@JessWaggs Would you have a moment to weigh in on this?

**Comment by JessWaggs** [comment]
Yes, Browse Collections link in the header should point to the A-Z collections list. Thanks!

**Comment by snehagunduraoUL** [comment]
@JessWaggs I have linked "Browse Collections" to A-Z list. But, which button/link would redirect us back to the homepage from A-Z list?

**Comment by JessWaggs** [comment]
@snehagunduraoUL I can't seem to get to the A-Z page, but the header on it should match the header on other non-homepages with a link back to the homepage via the site title.

We will be running usability studies on this site in the future and I'll be sure to include a task asking users to return to the homepage so we can ensure that path makes sense.

Thanks!
Screen Shot 2021-11-02 at 4 18 32 PM

**Comment by snehagunduraoUL** [comment]
Got it. I just have the changes in this repo (A-ZList). Thank you!

**Comment by snehagunduraoUL** [comment]
@rschwab Added link back to homepage. Could you please review it when you get a chance? Thank you.

**Review by rschwab — APPROVED** [review]
Great work.

**Pull request merged**
