### PR TITLE
Issue 135, redesign single image.

### PR DESCRIPTION
**Pull request by rschwab**
For https://github.com/UCSCLibrary/dams_project_mgmt/issues/135

Updated app/views/hyrax/base/show.html.erb and app/views/hyrax/base/_primary_media.html.erb to add html for css identifiers and a couple glyphicon span elements.

Updated app/assets/stylesheets/ucsc.css to style the image display.

### CODE REVIEW

**Comment by kellyChex** [comment]
@rschwab Could you attach a screenshot of what it looks like?

**Comment by NedHenry** [comment]
If you post a screencap, as an exercise I want to check out your branch in my dev environment and make sure what I see in my browser matches your screencap (just to make sure).

**Comment by rschwab** [comment]
Sorry, there are still some bugs in my local dev that make creating a work a little tricky. Here's the screenshot. Something we might need to consider is resizing the default display of large images.

Firefox_Screenshot_2019-12-20T21-58-14 259Z

**Comment by kellyChex** [comment]
This is great, thank you! @rschwab Is it possible to move the title over to line up with the right right side of the black box?

**Comment by rschwab** [comment]
Hi Kelly!

Happy to do that - but can you be more specific? I hadn't messed with the title at all, because it appeared to already match the mockup.

**Comment by kellyChex** [comment]
@rschwab I should have probably said move to the left more, not the right. Let's have @JessWaggs weigh in.

**Comment by JessWaggs** [comment]
I'm hoping to have the breadcrumbs, title, and "About this item" all be aligned (ultimately).

It looks like the title is aligning with the breadcrumbs, but the breadcrumbs are just farther to the right than they will ultimately be...

I don't have strong feelings about whether we should push the title further left now or wait until we're ready to work on breadcrumbs styling and align them at that point.

**Comment by rschwab** [comment]
I want to suggest we do this alignment as we go. Since the title is the only thing in this ticket, I'll work on aligning "About this item" on the metadata ticket and then the breadcrumbs when we get there.

**Comment by JessWaggs** [comment]
Aligning as we go sounds fine to me!

**Comment by kellyChex** [comment]
Ok, sounds like a plan.

**Comment by NedHenry** [comment]
I reverted this merge, and created a new pull request to merge the same branch into staging. I'm sure all the changes will be fine, but I'm getting in the habit of following our deployment workflow.

**Pull request merged**
