### PR TITLE
i459 fix collection search

### PR DESCRIPTION
**Pull request by bkiahstroud**
# Ticket: https://github.com/UCSCLibrary/dams_project_mgmt/issues/459

- Facets.js was overwriting the "cq" variable which searches collections.  Removed this code to enable searching within a collection.
- Collections "show_all" had a nil error if description was blank.  Added a check to .present? to resolve this.

# QA Testing instructions
- [ ] Searching within a collection returns matching results 

Screen_Shot_2021-11-16_at_2 09 20_PM

### CODE REVIEW

**Comment by rschwab** [comment]
This looks good to me. What do you think @snehagunduraoUL ?

**Comment by snehagunduraoUL** [comment]
Is this change available to test on http://ucsc-hyrax-staging.notch8.cloud ?

**Comment by bkiahstroud** [comment]
@snehagunduraoUL all the changes coming over today should be available to test on [our staging](http://ucsc-hyrax-staging.notch8.cloud/), yes

**Comment by snehagunduraoUL** [comment]
Awesome. Looks good to me too.

**Pull request merged**
